config/routes.rb
Rails.application.routes.draw do
  resources :paintings

end

app/models/painting.rb
class Painting < ActiveRecord::Base
  mount_uploader :image, PaintingUploader

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: [:show, :edit, :update, :destroy]

  # GET /paintings
  # GET /paintings.json
  def index
    @paintings = Painting.all
  end

  # GET /paintings/1
  # GET /paintings/1.json
  def show
  end

  # GET /paintings/new
  def new
    @painting = Painting.new
  end

  # GET /paintings/1/edit
  def edit
  end

  # POST /paintings
  # POST /paintings.json
  def create
    @painting = Painting.new(painting_params)

    respond_to do |format|
      if @painting.save
        format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
        format.json { render :show, status: :created, location: @painting }
      else
        format.html { render :new }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paintings/1
  # PATCH/PUT /paintings/1.json
  def update
    respond_to do |format|
      if @painting.update(painting_params)
        format.html { redirect_to @painting, notice: 'Painting was successfully updated.' }
        format.json { render :show, status: :ok, location: @painting }
      else
        format.html { render :edit }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1
  # DELETE /paintings/1.json
  def destroy
    @painting.destroy
    respond_to do |format|
      format.html { redirect_to paintings_url, notice: 'Painting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painting
      @painting = Painting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def painting_params
      params.require(:painting).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gill</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container" style="padding-top:20px;">
  <%= yield %>
</div>

</body>
</html>

app/views/paintings/_form.html.erb
<%= form_for@painting, html: { multipart: true } do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>

      <ul>
      <% @painting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paintings/edit.html.erb
<h1>Editing painting</h1>

<%= render 'form' %>

<%= link_to 'Show', @painting %> |
<%= link_to 'Back', paintings_path %>

app/views/paintings/index.html.erb
<h1>Listing paintings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paintings.each do |painting| %>
      <tr>
        <td><%= painting.name %></td>
        <td><%= painting.image %></td>
        <td><%= link_to 'Show', painting %></td>
        <td><%= link_to 'Edit', edit_painting_path(painting) %></td>
        <td><%= link_to 'Destroy', painting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Painting', new_painting_path %>

app/views/paintings/new.html.erb
<h1>New painting</h1>

<%= render 'form' %>

<%= link_to 'Back', paintings_path %>

app/views/paintings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @painting.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @painting.image %>
</p>

<%= link_to 'Edit', edit_painting_path(@painting) %> |
<%= link_to 'Back', paintings_path %>